export const values = {
  date: '',
  name: '',
  currency: '$',
  salary: 0,
  interest: 0,
  rental_income: 0,
  business_income: 0,
  total_income: 0,

  health_insurance: 0,
  mortgage_rent: 0,
  student_loan: 0,
  car_loan: 0,
  car_insurance: 0,
  credit_card_pay: 0,
  phone_bill: 0,
  internet_pay: 0,
  grocery: 0,
  water_bill: 0,
  fast_food: 0,
  electric_bill: 0,
  charity: 0,
  retail_pay: 0,
  loan_pay: 0,
  child_support: 0,
  custom_expense_1: '',
  custom_expense1_value: 0,
  custom_expense_2: '',
  custom_expense2_value: 0,
  custom_expense_3: '',
  custom_expense3_value: 0,
  custom_expense_4: '',
  custom_expense4_value: 0,
  total_expenses: 0,

  savings: 0,
  custom_stock_name1: '',
  custom_stock_amount_1: 0,
  stocks1: 0,
  custom_stock_name2: '',
  custom_stock_amount_2: 0,
  stocks2: 0,
  custom_stock_name3: '',
  custom_stock_amount_3: 0,
  stocks3: 0,

  custom_business_name1: '',
  custom_business_downpay_1: 0,
  business1: 0,
  custom_business_name2: '',
  custom_business_downpay_2: 0,
  business2: 0,
  custom_business_name3: '',
  custom_business_downpay_3: 0,
  business3: 0,
  custom_business_name4: '',
  custom_business_downpay_4: 0,
  business4: 0,

  home_mortgage: 0,
  school_loans: 0,
  car_loans: 0,
  credit_card: 0,
  retail_debt: 0,

  custom_liabilities_1: '',
  custom_liabilities_1_value: 0,
  custom_liabilities_2: '',
  custom_liabilities_2_value: 0,
  custom_liabilities_3: '',
  custom_liabilities_3_value: 0,
  custom_liabilities_4: '',
  custom_liabilities_4_value: 0,

  liabilities_name_1: '',
  liabilities1: 0,
  liabilities_name_2: '',
  liabilities2: 0,
  liabilities_name_3: '',
  liabilities3: 0,
  liabilities_name_4: '',
  liabilities4: 0,

  total_liabilities: 0,
};
